# Generated by Django 4.0.5 on 2022-06-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ph_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=145)),
                ('descripcion', models.CharField(max_length=256)),
                ('duracion', models.FloatField(default=0.0)),
                ('plataforma', models.CharField(blank=True, choices=[('SP', 'Spotify'), ('DZ', 'Deezer'), ('TD', 'Tidal'), ('YT', 'Youtube Music')], max_length=2, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='playlister',
            name='plataforma',
        ),
    ]
