# Generated by Django 4.0.5 on 2022-06-25 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ph_app', '0003_playlisterplaylist_delete_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=145)),
                ('descripcion', models.CharField(max_length=256)),
                ('canciones', models.IntegerField(default=0)),
                ('mood', models.CharField(blank=True, choices=[('Hap', 'Happy'), ('Chi', 'Chill'), ('Rom', 'Romantic'), ('Blu', 'Blue')], max_length=3, null=True)),
                ('plataforma', models.CharField(blank=True, choices=[('DZ', 'Deezer'), ('SP', 'Spotify'), ('TD', 'Tidal')], max_length=2, null=True)),
                ('link', models.CharField(max_length=100)),
                ('playlister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ph_app.playlister')),
            ],
        ),
        migrations.DeleteModel(
            name='PlaylisterPlaylist',
        ),
    ]
