# Generated by Django 4.0.5 on 2022-07-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ph_app', '0004_playlist_delete_playlisterplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='tag1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tag2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tag3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
