# Generated by Django 4.0.5 on 2022-07-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ph_app', '0005_playlist_tag1_playlist_tag2_playlist_tag3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='mood',
            field=models.CharField(blank=True, choices=[('Happy', 'Happy'), ('Chill', 'Chill'), ('Romantic', 'Romantic'), ('Blue', 'Blue')], max_length=40, null=True),
        ),
    ]
