# Generated by Django 4.0.5 on 2022-07-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ph_app', '0006_alter_playlist_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlister',
            name='descripcion',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
