# Generated by Django 4.0.5 on 2022-07-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ph_app', '0007_playlister_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlister',
            name='pais',
            field=models.CharField(blank=True, choices=[('AD', 'Andorra'), ('AF', 'Afghanistán'), ('AG', 'Antigua & Barbuda'), ('AI', 'Anguilla'), ('AL', 'Albania'), ('DE', 'Alemania'), ('DZ', 'Algeria'), ('AM', 'Armenia'), ('AN', 'Antillas Holandesas'), ('AO', 'Angola'), ('AQ', 'Antárctica'), ('AR', 'Argentina'), ('AT', 'Austria'), ('AU', 'Australia'), ('AW', 'Aruba'), ('AZ', 'Azerbaiyán'), ('BA', 'Bosnia y Herzegovina'), ('BB', 'Barbados'), ('BD', 'Bangladesh'), ('BE', 'Bélgica'), ('BF', 'Burkina Faso'), ('BG', 'Bulgaria'), ('BH', 'Baréin'), ('BI', 'Burundi'), ('BJ', 'Benín'), ('BM', 'Bermuda'), ('BN', 'Brunei Darussalam'), ('BO', 'Bolivia'), ('BR', 'Brasil'), ('BS', 'Bahama'), ('BT', 'Bhutan'), ('BV', 'Bouvet'), ('BW', 'Botswana'), ('BY', 'Bielorrusia'), ('BZ', 'Belice'), ('CA', 'Canadá'), ('CG', 'Congo'), ('CH', 'Suiza'), ('CI', 'Costa de Marfil'), ('CK', 'Islas Cook'), ('CL', 'Chile'), ('CM', 'Camerún'), ('CN', 'China'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('CY', 'Chipre'), ('DK', 'Dinamarca'), ('AE', 'Emiratos Árabes Unidos'), ('CC', 'Islas Cocos'), ('CX', 'Isla de Navidad'), ('CV', 'República de Cabo Verde'), ('CZ', 'República Checa'), ('DJ', 'República de Djibouti'), ('DO', 'República Dominicana'), ('CF', 'República Centroafricana'), ('AS', 'Samoa Americana'), ('DM', 'Mancomunidad de Dominica')], max_length=2, null=True),
        ),
    ]
